version: "3.8"

services:
  database_rentx:
    image: postgres
    container_name: database_compass
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker123
      - POSTGRES_DB=compass
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: compass
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    network_mode: host
volumes:
  pgdata:
    driver: local
